# Parameters used only by local costmap - updated online based on sensors readings
# For help and default parameters see:
# - http://wiki.ros.org/costmap_2d
# - http://wiki.ros.org/costmap_2d/hydro/obstacles
# - http://wiki.ros.org/costmap_2d/hydro/inflation

local_costmap:
    global_frame: odom
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    update_frequency: 2.0
    publish_frequency: 1.0

    plugins:
        - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

    obstacles_layer:
        observation_sources: scan
        scan:
            data_type: LaserScan
            topic: scan
            obstacle_range: 3.0
            raytrace_range: 3.5
            inf_is_valid: true

    inflation_layer:
        inflation_radius: 0.3
        cost_scaling_factor: 10